export const projects = [
  {
    id: 1,
    name: "Daily Meal",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/delivery.png",
    liveUrl: "https://food-delivery-app-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/food-delivery-app",
    tools: ["Next.js", "Node.js"],
  },
  {
    id: 2,
    name: "Talkline",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/talkline.png",
    liveUrl: "https://talkline-facebook-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/mern-talkline",
    tools: ["React.js", "Node.js"],
  },
  {
    id: 3,
    name: "YouTube Clone",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/youtube.png",
    liveUrl: "https://react-youtube-clone-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/react-youtube-clone",
    tools: ["React.js", "Firebase"],
  },
  {
    id: 4,
    name: "Stream",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/stream.png",
    liveUrl: "https://nextjs-stream-movie-app-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/Nextjs-stream-movie-app",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 5,
    name: "Realtor Clone",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/realtor.png",
    liveUrl: "https://react-realtor-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/React-realtor",
    tools: ["React.js", "Firebase"],
  },
  {
    id: 6,
    name: "Amazon Clone",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/amazon.png",
    liveUrl: "https://nextjs-amazon-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/nextjs-amazon-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 7,
    name: "Spotify Clone",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/spotify.png",
    liveUrl: "https://next-spotify-clone-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/Next-spotify-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 8,
    name: "Twitter Clone",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/twitter.png",
    liveUrl: "https://nextjs-twitter-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/nextjs-twitter-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 9,
    name: "Apple Clone",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/apple.png",
    liveUrl: "https://next-apple-clone-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/Next-apple-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 10,
    name: "Fun Filled",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    image: "/image/project/funfilled.png",
    liveUrl: "https://funfilled-app-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/funfilled-app-frontend",
    tools: ["React.js", "Node.js"],
  },
];
