export const projects = [
  {
    id: 1,
    name: "Daily Meal",
    description:
      "Food delivery app using Next.js,Node.js and payment method using Paypal and Stripe.",
    image: "/image/project/delivery.png",
    liveUrl: "https://food-delivery-app-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/food-delivery-app",
    tools: ["Next.js", "Node.js"],
  },
  {
    id: 2,
    name: "Talkline",
    description:
      "React social media app like facebook to create post,delete post,follow and un-follow friend,and chat with them.",
    image: "/image/project/talkline.png",
    liveUrl: "https://talkline-facebook-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/mern-talkline",
    tools: ["React.js", "Node.js"],
  },
  {
    id: 3,
    name: "YouTube Clone",
    description: "Youtube clone to search,watch and comment on videos.",
    image: "/image/project/youtube.png",
    liveUrl: "https://react-youtube-clone-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/react-youtube-clone",
    tools: ["React.js", "Firebase"],
  },
  {
    id: 4,
    name: "Stream",
    description:
      "Netflix clone to subscribe as a user and watch movie trailers.",
    image: "/image/project/stream.png",
    liveUrl: "https://nextjs-stream-movie-app-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/Nextjs-stream-movie-app",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 5,
    name: "Realtor Clone",
    description: "Realtor clone to add,delete houses and contact owners.",
    image: "/image/project/realtor.png",
    liveUrl: "https://react-realtor-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/React-realtor",
    tools: ["React.js", "Firebase"],
  },
  {
    id: 6,
    name: "Amazon Clone",
    description:
      "Amazon clone for buying products using stripe payment method.",
    image: "/image/project/amazon.png",
    liveUrl: "https://nextjs-amazon-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/nextjs-amazon-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 7,
    name: "Spotify Clone",
    description:
      "Spotify clone with the same functionality for listening songs.",
    image: "/image/project/spotify.png",
    liveUrl: "https://next-spotify-clone-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/Next-spotify-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 8,
    name: "Shoppers",
    description:
      "An e-commerce app using React,Firebase and Node.js for buying clothes.",
    image: "/image/project/shoppers.png",
    liveUrl: "https://react-shopper-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/React-Shopper",
    tools: ["React.js", "Firebase", "Node.js"],
  },
  {
    id: 9,
    name: "Whatsapp Clone",
    description: "Whatsapp clone for chatting with friends by add their email.",
    image: "/image/project/whatsapp.png",
    liveUrl: "https://next-js-whatsapp-clone-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/Next.js-whatsapp-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 10,
    name: "Twitter Clone",
    description: "Twitter clone for adding,liking and commenting on posts.",
    image: "/image/project/twitter.png",
    liveUrl: "https://nextjs-twitter-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/nextjs-twitter-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 11,
    name: "Apple Clone",
    description:
      "Apple clone for buying apple products such as Laptop,iPad,iPhone and Watches.",
    image: "/image/project/apple.png",
    liveUrl: "https://next-apple-clone-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/Next-apple-clone",
    tools: ["Next.js", "Firebase"],
  },
  {
    id: 12,
    name: "Fun Filled",
    description: "Social media app for posting fun moments.",
    image: "/image/project/funfilled.png",
    liveUrl: "https://funfilled-app-samuelberhane.vercel.app",
    gitUrl: "https://github.com/samuelberhane/funfilled-app-frontend",
    tools: ["React.js", "Node.js"],
  },
];
