import Head from "next/head";
import {
  Banner,
  Header,
  Skills,
  Projects,
  Services,
  Contact,
  Footer,
} from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Samuel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-[Crimson Text] bg-black text-white">
        <Header />
        <Banner />
        <Skills />
        <Projects />
        <Services />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
